language: python

python:
  - 3.6

env:
  - PIPENV_SHELL_COMPAT=true PIPENV_COLORBLIND=true PIPENV_NOSPIN=true

install:
  - pip install 'pipenv==8.1.3'
  - pipenv install --system -d
  #sddsf

script:
  - pytest

notifications:
  email:
    on_success: never
    on_failure: change